chat-prefix: "&8[&dAshUtils&8]"
discord-broadcast-cmd: "discord broadcast"
head-worth: 100
currency-symbol: $
vanish-on-login-group: vol
xp-sell-worth: 2
xp-buy-cost: 2.2
xp-maximum-buy: 10000
join-message: "&a&l+ &r&e{USERNAME}"
quit-message: "&c&l- &r&e{USERNAME}"
discord-staffchat-cmd: "a"