chat-prefix: "&8[&dAshUtils&8]"
head-worth: 100
currency-symbol: $
vanish-on-login-group: vol
join-message: "&a&l+ &r&e{USERNAME}"
quit-message: "&c&l- &r&e{USERNAME}"
xp:
  buy-cost: 2.2
  sell-worth: 2
  maximum-buy: 10000
discord:
  broadcast-cmd: "discord broadcast"
  staffchat-cmd: "a"
  report-webhook: "PUT APPLICATION/JSON WEBHOOK URL HERE"