name: AshUtils
main: uk.asheiou.ashutils.AshUtils
version: ${project.version}
author: Asheiou
api-version: 1.21.5
softdepend: [Vault, Essentials, DiscordSRV]
website: https://mc.asheiou.uk
description: >
             The MC.Asheiou.UK bespoke everything-plugin!
commands:
  headsell:
    aliases: sellhead
    description: Sell any unwanted player heads back to the server!
    usage: /<command> <amount/all>
    permisison: ashutils.headsell
    permission-message: You don't have ashutils.headsell.
  ashutils:
    aliases: util
    description: Admin command.
    usage: /<command> reload
    permission: ashutils.admin
    permission-message: You don't have ashutils.admin.

permissions:
  ashutils.headsell:
    description: Allows head sell
    default: true
  ashutils.admin:
    description: Allows /ashutils
    default: op
        