name: AshUtils
main: uk.asheiou.ashutils.AshUtils
version: ${project.version}
author: Asheiou
api-version: 1.18
website: https://mc.asheiou.uk
description: >
             The MC.Asheiou.UK bespoke everything-plugin!
commands:
  restartonempty:
    aliases: [roe, ronempty]
    description: Set the server to restart on empty.
    usage: /<command> [true/false/status]
    permission: restartonempty.use
    permission-message: You don't have restartonempty.use.

permissions:
  restartonempty.use:
    description: Allows use of the plugin
    default: op
        